### ISSUE TITLE
gives error `Unclosed client session` with python 3.11

### ISSUE THREAD

**Issue by web3dopamine** [dex-guru/meta-aggregation-api#24]
I am getting the following error while running the repo with python 3.11
```
ERROR:    Application startup failed. Exiting.
2023-05-04 19:54:45,526 - base_events.py:1771:default_exception_handler - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1067dbd10>
```

I assume the error is coming from `base_provider.py` (not a python dev here) as the session is not closed

**Comment by web3dopamine** [comment]
![image](https://user-images.githubusercontent.com/14943387/236378850-c71e501e-6c92-4026-b26c-57a2a2f68155.png)

**Comment by web3dopamine** [comment]
its doesnt run with python 3.10 also

**Comment by web3dopamine** [comment]
![image](https://github.com/dex-guru/meta-aggregation-api/assets/14943387/66e2c377-cb54-4202-9fb4-4ce8d68fe444)
same error in vscode for better visual

**Comment by shestakoven** [comment]
Under the hood we use our public SDK, that requires API key from https://developers.dex.guru 
so, to run the app, you need to get your API key and pass it in your ENV or set it in app config https://github.com/dex-guru/meta-aggregation-api/blob/c7938de3ca04f1c4f612850df5500a0d8eb0146a/meta_aggregation_api/config/__init__.py#L17

**Comment by web3dopamine** [comment]
still didnt work.

**Comment by web3dopamine** [comment]
i made some changes regarding `httpUrl` to `AnyHttpUrl` because i was getting error for that.

But i asked my friend to send his file repo exactly the same and was able to run locally.

**Comment by web3dopamine** [comment]
thanks it worked
